#management:
#  endpoint:
#    health:
#      show-details: always
#      show-components: always
#  endpoints:
#    jmx:
#      exposure:
#        include: *
#    web:
#      exposure:
#        include: *
#  #        include: prometheus